# Generated by Django 4.0.5 on 2022-06-29 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reminder.timestamp')),
                ('mile_list', models.JSONField()),
            ],
            bases=('reminder.timestamp',),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('timestamp_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reminder.timestamp')),
                ('title', models.CharField(max_length=200)),
                ('is_notification', models.BooleanField(default=False)),
                ('notifications', models.JSONField(null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('is_achieve', models.BooleanField(default=False)),
                ('achieve_date', models.DateTimeField(blank=True, null=True)),
                ('milestones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.milestone')),
            ],
            bases=('reminder.timestamp',),
        ),
    ]
