# Generated by Django 4.0.5 on 2022-06-29 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='milestones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reminder.milestone'),
        ),
    ]
